"""empty message

Revision ID: 0d66bcca6ea7
Revises: 5c3f630ca3b2
Create Date: 2024-04-19 18:56:01.327453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d66bcca6ea7'
down_revision = '5c3f630ca3b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_won', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_column('game_won')

    # ### end Alembic commands ###
