"""empty message

Revision ID: 5c3f630ca3b2
Revises: 2e3392d35b5c
Create Date: 2024-04-19 18:52:08.205444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c3f630ca3b2'
down_revision = '2e3392d35b5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('num_turns', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scores'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scores')
    # ### end Alembic commands ###
